# Generated by Django 5.1.6 on 2025-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=25)),
                ('done', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
